/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-20 02:44:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   #list-area{\r\n");
      out.write("       border:1px solid white;\r\n");
      out.write("       text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   #list-area>tbody>tr:hover{\r\n");
      out.write("       background: darkgray;\r\n");
      out.write("       cursor: pointer;\r\n");
      out.write("   }\r\n");
      out.write("   #paging-area a{\r\n");
      out.write("       color: white;\r\n");
      out.write("       text-decoration: none;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <h1 align=\"center\">게시판</h1>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <!--검색영역-->\r\n");
      out.write("        <div id=\"search-area\" align=\"center\">\r\n");
      out.write("            <form action=\"search.bo\">\r\n");
      out.write("                <select name=\"condition\">\r\n");
      out.write("                    <option value=\"writer\">작성자</option>\r\n");
      out.write("                    <option value=\"title\">제목</option>\r\n");
      out.write("                    <option value=\"content\">내용</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"text\" name=\"keyword\">\r\n");
      out.write("                <button type=\"submit\">검색</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("\r\n");
      out.write("        <table id=\"list-area\" align=\"center\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>글번호</th>\r\n");
      out.write("                    <th width=\"400\">제목</th>\r\n");
      out.write("                    <th>작성자</th>\r\n");
      out.write("                    <th>조회수</th>\r\n");
      out.write("                    <th>작성일</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>글제목입니다.</td>\r\n");
      out.write("                    <td>user02</td>\r\n");
      out.write("                    <td>10</td>\r\n");
      out.write("                    <td>2020-10-20</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>제목임둥</td>\r\n");
      out.write("                    <td>admin</td>\r\n");
      out.write("                    <td>20</td>\r\n");
      out.write("                    <td>2020-10-01</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>제목이라고</td>\r\n");
      out.write("                    <td>user01</td>\r\n");
      out.write("                    <td>30</td>\r\n");
      out.write("                    <td>2020-09-10</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"paging-area\" align=\"center\">\r\n");
      out.write("            <a href=\"\">[이전]</a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"\">[1]</a>\r\n");
      out.write("            <a href=\"\">[2]</a>\r\n");
      out.write("            <a href=\"\">[3]</a>\r\n");
      out.write("            <a href=\"\">[4]</a>\r\n");
      out.write("            <a href=\"\">[5]</a>\r\n");
      out.write("            <a href=\"\">[다음]</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><Br>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
